# Site wide configuration

title:            Alberto Moral
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Alberto Moral
  avatar: bio-photo.jpg
  bio: "Mobile Developer"
  email: alberto.moral.g@gmail.com
  disqus-shortname:
  twitter: AlbertMoral
  facebook: alberto.moral.gomez
  google:
    plus: AlbertoMoralGomez
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: MoralAlberto
  stackoverflow: 4409134/moral
  linkedin: albertomoral
  xing: #username
  instagram: albertmoral
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
